name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt install -y meson
    - name: Build and Test CMake
      run: |
        CC=clang CXX=clang++ cmake -B build-cmake -G Ninja -DFADEC_ENCODE2=ON
        cmake --build build-cmake -v
        ctest --test-dir build-cmake -V
    - name: Build and Test Meson
      run: |
        mkdir build-meson; CC=clang CXX=clang++ meson -Dbuildtype=debugoptimized -Dwith_encode2=true build-meson
        ninja -v -C build-meson
        meson test -v -C build-meson
    - name: Build and Test Rust
      run: cargo test
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: pip install ninja meson
    - name: Build and Test CMake
      run: |
        cmake -B build-cmake -DFADEC_ENCODE2=ON
        cmake --build build-cmake -v
        ctest --test-dir build-cmake -V -C Debug
    - name: Build and Test Meson
      run: |
        mkdir build-meson; meson setup --vsenv -Dbuildtype=debugoptimized -Dwith_encode2=true build-meson
        meson compile -v -C build-meson
        meson test -v -C build-meson
    - name: Build and Test Rust
      run: cargo test
